"""
ScoutingReportAgent — ReACT-mode report generator using graph retrieval.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from models import PlayerPersona, RoundSummary
from server.graphrag.graph_builder import InMemoryGraph
from server.graphrag.retriever import GraphRetriever
from server.utils.llm_client import get_llm_client
from server.utils.logger import get_logger

log = get_logger("report_agent")

REPORT_SYSTEM_PROMPT = """You are a professional football scout AI. Generate a scouting report
based on the simulation data and player profile provided.

Structure your report as markdown with these sections:
## Player Overview
## Simulation Summary
## Tactical Fit Analysis
## Strengths
## Weaknesses
## Risk Assessment (injury, form, adaptability)
## Recruitment Recommendation
## Confidence Score (0-100%)

Be specific, use statistics from the simulation, and provide actionable insights."""


class ReportAgent:
    """Generates scouting reports from simulation results."""

    def __init__(self, graph: InMemoryGraph | None = None):
        self._llm = get_llm_client()
        self._graph = graph
        self._retriever = GraphRetriever(graph) if graph else None

    def generate_report(
        self,
        persona: PlayerPersona,
        sim_results: Dict[str, Any],
        task_id: str = "",
        grade: float = 0.0,
    ) -> str:
        context_parts = [
            f"Player: {persona.name} ({persona.position}, {persona.nationality}, age {persona.age})",
            f"Bio: {persona.bio}",
            f"MBTI: {persona.mbti_tag}, Decision style: {persona.decision_style}",
            f"Pressure response: {persona.pressure_response}",
            f"\nTrait vector: {json.dumps(dict(zip(persona.trait_names(), persona.trait_vector())))}",
            f"\nSimulation results: {json.dumps(sim_results, default=str)[:2000]}",
            f"\nTask: {task_id}, Grade: {grade:.2f}",
        ]

        # Add graph context if available
        if self._retriever:
            graph_ctx = self._retriever.retrieve(persona.player_id)
            context_parts.append(f"\nGraph context:\n{graph_ctx}")

        try:
            messages = [
                {"role": "system", "content": REPORT_SYSTEM_PROMPT},
                {"role": "user", "content": "\n".join(context_parts)},
            ]
            report = self._llm.chat(messages, max_tokens=2048)
            log.info(f"Generated scouting report for {persona.name} ({len(report)} chars)")
            return report
        except Exception as exc:
            log.warning(f"LLM report generation failed: {exc}. Using template.")
            return self._template_report(persona, sim_results, grade)

    @staticmethod
    def _template_report(
        persona: PlayerPersona,
        sim_results: Dict[str, Any],
        grade: float,
    ) -> str:
        metrics = sim_results.get("performance_metrics", {})
        return f"""## Scouting Report: {persona.name}

### Player Overview
- **Position:** {persona.position}
- **Nationality:** {persona.nationality}
- **Age:** {persona.age}
- **Profile:** {persona.bio}
- **Decision Style:** {persona.decision_style}
- **Pressure Response:** {persona.pressure_response}

### Simulation Summary
- **Overall Grade:** {grade:.2f} / 1.00
- **Output Score:** {metrics.get('output_score', 0):.2f}
- **Tactical Fit:** {metrics.get('tactical_fit', 0):.2f}
- **Coherence:** {metrics.get('coherence_score', 0):.2f}

### Key Traits
| Trait | Rating |
|-------|--------|
| Speed | {persona.speed:.2f} |
| Stamina | {persona.stamina:.2f} |
| Technical | {persona.technical:.2f} |
| Creativity | {persona.creativity:.2f} |
| Leadership | {persona.leadership:.2f} |
| Big Game | {persona.big_game_performance:.2f} |

### Recommendation
{'RECOMMENDED for signing.' if grade >= 0.6 else 'FURTHER EVALUATION NEEDED.' if grade >= 0.4 else 'NOT RECOMMENDED at this time.'}

*Report generated by Fidenz Athlete OS Scouting AI*
"""
